### PR TITLE
adds more content to README

### PR DESCRIPTION
**Pull request by razzlepdx**
This is a start on resolving issue #44  -  I mostly wanted to get some feedback before I added more content to the README.  

Can you take a look, especially at the brief and user stories sections, and let me know what you think?  Feel free to make any changes or leave some notes in Slack and I'm happy to fix them.  

Items still to be added:
- tech stack - add to brief section
- pageflow diagrams using draw.io
- contributors
- license information

### CODE REVIEW

**Comment by reuben-jones** [comment]
Looks good @razzlepdx. Instead of making changes, I'll post a couple of suggestions in Slack. See what you think. :)

**Review by reuben-jones — APPROVED** [review]
I'll leave a couple of comments in the Slack channel. Just a couple of conceptual things.

**Review by jsjoeio — APPROVED** [review]
Looks great!

**Comment by razzlepdx** [comment]
Ok, I think this README is in pretty good shape now.  The only item left is to add pageflow diagrams, but I am going to work on that as a separate issue - #53.  If you guys have any changes or suggestions, let me know!

**Review by reuben-jones — APPROVED** [review]

**Review by jsjoeio — APPROVED** [review]
I think it looks great Rachel!

**Pull request merged**
